# Train Fused_CNN_ResNet50_CLIP_ViT_512_Concat
# python main.py --config-file "configs/custom/experiment_1.yaml" --no-tf-test True
MODEL:
  TYPE: "MyModel"
  NAME: "Fused_CNN_ResNet50_CLIP_ViT_512_Concat"
  RESUME: False
  BACKBONE:
    PRETRAINED: True
    FREEZE: True

DATASET:
  NAME: "CNNSpot"
  DATA_DIR: "/kaggle/input/cnnspot/cnn_spot"
  NUM_CLASSES: 2

DATALOADER:
  BATCH_SIZE: 128

TRANSFORM:
  TRANSFORMS: ["resize", "random_flip", "contrast", "to_tensor", "normalize"]
  NORMALIZE_BACKBONE: True
  INPUT_SIZE: (224, 224)
  # GAUSSIAN BLUR
  GB_P: 0.5
  GB_K: 21
  GB_SIGMA: (0.1, 3.0)
  # JPEG COMPRESSION
  JPEG_P: 0.5
  JPEG_QUALITY: (30, 99)
  # CONTRAST
  CONTRAST: (0.6, 1.4)
  CONTRAST_P: 1.0
  # TEST
  NO_TRANSFORM_TEST: True

TRAINER:
  TYPE: 0
  USE_CUDA: True
  IS_TRAIN: TRUE
  NUM_EPOCHS: 1
  NO_TEST: True # val after epoch and test after train
  TEST_FINAL_MODEL: "best_val"
  OPTIM:
    NAME: "sgd"
    LR: 0.002
    STEPSIZE: [20]

EVALUATOR:
  TYPE: 0
  COMPUTE_CONFUSION_MATRIX: False
