# Test
# python main.py --config-file "configs/custom/experiment_22.yaml" --eval-only
MODEL:
  TYPE: "MyModelUponAveragingModel"
  NAME: "Fused_CNN_ResNet50_CNN_ResNet50_512_Concat"
  MODEL_DIR: "/kaggle/input/models/anhphmminh/fused-hf-lf-resnet50-no-aug/pytorch/default/1"
  MODEL_NAME: "model-best.pth.tar"
  BACKBONE:
    PRETRAINED: False
    FREEZE: True
  MyModelUponAveragingModel:
    PRETRAINED_PATH: "/kaggle/input/models/myxxanaplt/train-high-freq-cnndet/pytorch/default/1/model-best.pth.tar"

DATASET:
  NAME: "CNNSpotTestSet"
  DATA_DIR: ""
  NUM_CLASSES: 2

DATALOADER:
  BATCH_SIZE: 128

TRANSFORM:
  TRANSFORMS: ["resize", "to_tensor", "normalize"]
  NORMALIZE_BACKBONE: True
  INPUT_SIZE: (224, 224)
  # GAUSSIAN BLUR
  GB_P: 0.5
  GB_K: 21
  GB_SIGMA: (0.1, 3.0)
  # JPEG COMPRESSION
  JPEG_P: 0.5
  JPEG_QUALITY: (30, 99)
  # TEST
  NO_TRANSFORM_TEST: True

TRAINER:
  TYPE: 0
  USE_CUDA: True
  IS_TRAIN: False
  NUM_EPOCHS: 2
  NO_TEST: False # val after epoch and test after train
  TEST_FINAL_MODEL: "best_val"
  OPTIM:
    NAME: "sgd"
    LR: 0.002
    STEPSIZE: [20]

EVALUATOR:
  TYPE: 0
  COMPUTE_CONFUSION_MATRIX: False
