# my_project/config.py
from yacs.config import CfgNode as CN


_C = CN()

# MODEL
_C.MODEL = CN()
_C.MODEL.TYPE = "MyModel"
_C.MODEL.NAME = "Fused_CNN_ResNet50_CLIP_ViT_512_Concat"
_C.MODEL.OUTPUT_DIR = f"output/{_C.MODEL.TYPE}/{_C.MODEL.NAME}"
_C.MODEL.MODEL_PATH = f"output/{_C.MODEL.TYPE}/{_C.MODEL.NAME}/model/model-best.pth.tar"
# BACKBONE
_C.MODEL.BACKBONE = CN()
_C.MODEL.BACKBONE.PRETRAINED = False
_C.MODEL.BACKBONE.FREEZE = True

# DATASET
_C.DATASET = CN()
_C.DATASET.NUM_CLASSES = 2

# DATALOADER
_C.DATALOADER = CN()

# TRANSFORM
_C.TRANSFORM = CN()
# TRAIN
# VAL
# TEST

# TRAINER
_C.TRAINER = CN()
_C.TRAINER.USE_CUDA = True

# EVALUATOR
_C.EVALUATOR = CN()
